version: '3'
services:
    db:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: hackathon
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    api:
        depends_on:
            - db
        image: node:latest
        ports:
            - 3000:3000
        volumes:
            - ./:/usr/app
        command: bash -c "cd /usr/app && npm i && npm run dev"
        links:
            - db:db
